import { SiteConfig, PricingConfig } from '../types';

export const siteConfig: SiteConfig = {
  businessName: 'TRAVEL JUST',
  tagline: 'JUST BOOK * JUST TRAVEL',
  description: 'Reliable rides for local travel, one-way drops, round trips, and airport transfers.',
  siteUrl: 'https://www.traveljust.in',
  contact: {
    phone: '+91 9740754400',
    whatsapp: '+91 9740754400',
    email: 'traveljustmysuru@gmail.com',
    businessHours: '24/7 Customer Support & Service',
  },
  socialProfiles: [
    { platform: 'Website', url: 'https://www.traveljust.in' },
    { platform: 'WhatsApp', url: 'https://wa.me/919740754400' },
    { platform: 'Customer Care', url: 'tel:+919740754400' },
  ],
};

export const defaultPricingConfig: PricingConfig = {
  currencySymbol: 'Rs. ',
  currencyCode: 'RS',
  baseFare: 300,
  perKmFare: 13.0,
  perHourFare: 150,
  airportSurcharge: 100,
  waitingChargePerHour: 100,
  additionalPassengerCharge: 50,
  nightChargePercentage: 10, // 10% surcharge for night trips
  extraStopCharge: 100,
  gstPercentage: 5,
  vehiclePricing: {
    'sedan-4-1': {
      vehicleId: 'sedan-4-1',
      baseFare: 599,
      localPerKmRate: 12.0,
      localDriverAllowance: 399,
      oneWayPerKmRate: 13.0,
      oneWayDriverAllowance: 300,
      airportPerKmRate: 13.0,
      airportDriverAllowance: 250,
      perKmFare: 12.0,
      perHourFare: 50,
      driverAllowancePerDay: 399,
      airportBaseFare: 699,
      minKmPerDay: 300,
      nightChargePercentage: 10,
    },
    'suv-6-1': {
      vehicleId: 'suv-6-1',
      baseFare: 599,
      localPerKmRate: 14.0,
      localDriverAllowance: 499,
      oneWayPerKmRate: 16.5,
      oneWayDriverAllowance: 350,
      airportPerKmRate: 16.0,
      airportDriverAllowance: 300,
      perKmFare: 14.0,
      perHourFare: 75,
      driverAllowancePerDay: 499,
      airportBaseFare: 999,
      minKmPerDay: 300,
      nightChargePercentage: 10,
    },
    'innova': {
      vehicleId: 'innova',
      baseFare: 599,
      localPerKmRate: 20.0,
      localDriverAllowance: 499,
      oneWayPerKmRate: 20.0,
      oneWayDriverAllowance: 450,
      airportPerKmRate: 20.0,
      airportDriverAllowance: 350,
      perKmFare: 20.0,
      perHourFare: 85,
      driverAllowancePerDay: 499,
      airportBaseFare: 1199,
      minKmPerDay: 300,
      nightChargePercentage: 15,
    },
    'innova-crysta': {
      vehicleId: 'innova-crysta',
      baseFare: 599,
      localPerKmRate: 18.0,
      localDriverAllowance: 499,
      oneWayPerKmRate: 25.0,
      oneWayDriverAllowance: 500,
      airportPerKmRate: 24.0,
      airportDriverAllowance: 400,
      perKmFare: 18.0,
      perHourFare: 95,
      driverAllowancePerDay: 499,
      airportBaseFare: 1599,
      minKmPerDay: 300,
      nightChargePercentage: 15,
    },
    'tempo-traveller-12-1': {
      vehicleId: 'tempo-traveller-12-1',
      baseFare: 1200,
      localPerKmRate: 39.0,
      localDriverAllowance: 799,
      oneWayPerKmRate: 33.0,
      oneWayDriverAllowance: 700,
      airportPerKmRate: 30.0,
      airportDriverAllowance: 500,
      perKmFare: 39.0,
      perHourFare: 120,
      driverAllowancePerDay: 799,
      airportBaseFare: 2499,
      minKmPerDay: 300,
      nightChargePercentage: 15,
    },
  },
};
