import { SiteConfig, PricingConfig } from '../types';

export const siteConfig: SiteConfig = {
  businessName: 'TRAVEL JUST',
  tagline: 'JUST BOOK * JUST TRAVEL',
  description: 'Reliable rides for local travel, one-way drops, round trips, and airport transfers.',
  siteUrl: 'https://www.traveljust.in',
  contact: {
    phone: '+91 9740754400',
    whatsapp: '+91 9740754400',
    email: 'traveljustmysuru@gmail.com',
    businessHours: '24/7 Customer Support & Service',
  },
  socialProfiles: [
    { platform: 'Website', url: 'https://www.traveljust.in' },
    { platform: 'WhatsApp', url: 'https://wa.me/919740754400' },
    { platform: 'Customer Care', url: 'tel:+919740754400' },
  ],
};

export const defaultPricingConfig: PricingConfig = {
  currencySymbol: 'Rs. ',
  currencyCode: 'RS',
  baseFare: 300,
  perKmFare: 13.0,
  perHourFare: 150,
  airportSurcharge: 100,
  waitingChargePerHour: 100,
  additionalPassengerCharge: 50,
  nightChargePercentage: 10, // 10% surcharge for night trips
  extraStopCharge: 100,
  gstPercentage: 5,
  vehiclePricing: {
    'sedan-4-1': {
      vehicleId: 'sedan-4-1',
      baseFare: 300,
      localPerKmRate: 13.0,
      localDriverAllowance: 250,
      oneWayPerKmRate: 13.0,
      oneWayDriverAllowance: 300,
      airportPerKmRate: 13.0,
      airportDriverAllowance: 250,
      perKmFare: 13.0,
      perHourFare: 150,
      driverAllowancePerDay: 300,
      airportBaseFare: 699,
      minKmPerDay: 300,
      nightChargePercentage: 10,
    },
    'toyota-etios': {
      vehicleId: 'toyota-etios',
      baseFare: 300,
      localPerKmRate: 13.0,
      localDriverAllowance: 250,
      oneWayPerKmRate: 13.0,
      oneWayDriverAllowance: 300,
      airportPerKmRate: 13.0,
      airportDriverAllowance: 250,
      perKmFare: 13.0,
      perHourFare: 150,
      driverAllowancePerDay: 300,
      airportBaseFare: 699,
      minKmPerDay: 300,
      nightChargePercentage: 10,
    },
    'swift-desire': {
      vehicleId: 'swift-desire',
      baseFare: 300,
      localPerKmRate: 13.0,
      localDriverAllowance: 250,
      oneWayPerKmRate: 13.5,
      oneWayDriverAllowance: 300,
      airportPerKmRate: 13.5,
      airportDriverAllowance: 250,
      perKmFare: 13.0,
      perHourFare: 150,
      driverAllowancePerDay: 300,
      airportBaseFare: 699,
      minKmPerDay: 300,
      nightChargePercentage: 10,
    },
    'ertiga': {
      vehicleId: 'ertiga',
      baseFare: 450,
      localPerKmRate: 15.0,
      localDriverAllowance: 300,
      oneWayPerKmRate: 16.5,
      oneWayDriverAllowance: 350,
      airportPerKmRate: 16.0,
      airportDriverAllowance: 300,
      perKmFare: 14.5,
      perHourFare: 200,
      driverAllowancePerDay: 400,
      airportBaseFare: 999,
      minKmPerDay: 300,
      nightChargePercentage: 10,
    },
    'innova': {
      vehicleId: 'innova',
      baseFare: 550,
      localPerKmRate: 18.0,
      localDriverAllowance: 350,
      oneWayPerKmRate: 20.0,
      oneWayDriverAllowance: 450,
      airportPerKmRate: 19.0,
      airportDriverAllowance: 350,
      perKmFare: 17.5,
      perHourFare: 240,
      driverAllowancePerDay: 450,
      airportBaseFare: 1199,
      minKmPerDay: 300,
      nightChargePercentage: 15,
    },
    'innova-6-1': {
      vehicleId: 'innova-6-1',
      baseFare: 550,
      localPerKmRate: 18.0,
      localDriverAllowance: 350,
      oneWayPerKmRate: 20.0,
      oneWayDriverAllowance: 450,
      airportPerKmRate: 19.0,
      airportDriverAllowance: 350,
      perKmFare: 17.5,
      perHourFare: 240,
      driverAllowancePerDay: 450,
      airportBaseFare: 1199,
      minKmPerDay: 300,
      nightChargePercentage: 15,
    },
    'innova-7-1': {
      vehicleId: 'innova-7-1',
      baseFare: 600,
      localPerKmRate: 19.0,
      localDriverAllowance: 350,
      oneWayPerKmRate: 21.0,
      oneWayDriverAllowance: 450,
      airportPerKmRate: 20.0,
      airportDriverAllowance: 350,
      perKmFare: 18.5,
      perHourFare: 250,
      driverAllowancePerDay: 450,
      airportBaseFare: 1249,
      minKmPerDay: 300,
      nightChargePercentage: 15,
    },
    'innova-crysta': {
      vehicleId: 'innova-crysta',
      baseFare: 800,
      localPerKmRate: 23.0,
      localDriverAllowance: 400,
      oneWayPerKmRate: 25.0,
      oneWayDriverAllowance: 500,
      airportPerKmRate: 24.0,
      airportDriverAllowance: 400,
      perKmFare: 22.0,
      perHourFare: 320,
      driverAllowancePerDay: 500,
      airportBaseFare: 1599,
      minKmPerDay: 300,
      nightChargePercentage: 15,
    },
    'tempo-traveller-12-1': {
      vehicleId: 'tempo-traveller-12-1',
      baseFare: 1200,
      localPerKmRate: 30.0,
      localDriverAllowance: 500,
      oneWayPerKmRate: 33.0,
      oneWayDriverAllowance: 700,
      airportPerKmRate: 30.0,
      airportDriverAllowance: 500,
      perKmFare: 28.0,
      perHourFare: 450,
      driverAllowancePerDay: 700,
      airportBaseFare: 2499,
      minKmPerDay: 300,
      nightChargePercentage: 15,
    },
  },
};
